### PR TITLE
Fixed Title with xml:space test.

### LINKED ISSUE #1921: Fix Title with xml:space="preserve" test
In `title_info_spec.rb`.

### PR DESCRIPTION
**Pull request by justinlittman**
Also, added custom hash matcher that ignores order.

closes #1921

## Why was this change made?
* Less broken tests = better mapping.
* Show diff when comparing cocina hashes for easier debugging.

## How was this change tested?
Unit, sdr-deploy

## Which documentation and/or configurations were updated?
NA

### CODE REVIEW

**Comment by justinlittman** [comment]
Before:
```
Status (n=100000):
  Success:   98117 (98.117%)
  Different: 1334 (1.334%)
  To Cocina error:     18 (0.018%)
  To Fedora error:     0 (0.0%)
  Missing:     531 (0.531%)
```

After:
```
Status (n=100000):
  Success:   98117 (98.117%)
  Different: 1334 (1.334%)
  To Cocina error:     18 (0.018%)
  To Fedora error:     0 (0.0%)
  Missing:     531 (0.531%)
```

File: app/services/cocina/from_fedora/descriptive/title_builder.rb [hunk 1]
```diff
@@ -58,31 +58,36 @@ def simple_title?(children)
...
+          end
         end
 
         def note(child_nodes)
           unsortable = child_nodes.select { |node| node.name == 'nonSort' }
           return nil if unsortable.empty?
 
           count = unsortable.sum do |node|
-            add = node.text.end_with?('-') || node.text.end_with?("'") ? 0 : 1
+            add = node.text.end_with?('-') || node.text.end_with?("'") || node.text.end_with?(' ') ? 0 : 1
```
Comment (jcoyne) [inline app/services/cocina/from_fedora/descriptive/title_builder.rb:90]: How about:
```ruby
last_character = node.text.slice(-1, 1)
add = ['-', "'", ' '].include?(last_character) ? 0 : 1
```

**Review by jcoyne — APPROVED** [review]
