### PR TITLE
Handle objects that don't provide access subschema

### LINKED ISSUE #776: [dor-services-app/stage] NoMethodError: undefined method `access' for nil:NilClass
## Backtrace

    line 89 of [PROJECT_ROOT]/app/services/cocina/object_creator.rb: block in create_dro
    line 86 of [PROJECT_ROOT]/app/services/cocina/object_creator.rb: tap
    line 86 of [PROJECT_ROOT]/app/services/cocina/object_creator.rb: create_dro

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50568/faults/62496152)

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?

This indicates they should use the default provided by the APO

Fixes #776

## Was the API documentation (openapi.yml) updated?
no

## Does this change affect how this application integrates with other services?

yes, it fixes it.
If so, please confirm change was tested on stage and/or test added to sul-dlss/infrastructure-integration-test.

### CODE REVIEW

File: app/services/validate_dark_service.rb [hunk 1]
```diff
@@ -14,7 +14,7 @@ def valid?
   def invalid_files
     @invalid_files ||= begin
       [].tap do |invalid_files|
-        next unless item.access.access == 'dark'
+        next unless item.access&.access == 'dark'
```
Comment (justinlittman) [inline app/services/validate_dark_service.rb:17]: access has a default of dark, so I don't think this is necessary but certainly won't hurt.

Comment (jcoyne) [reply app/services/validate_dark_service.rb:17]: I think it only defaults if access is provided at all.
