### PR TITLE
fix subject name mapping from fedora when name has no type

### LINKED ISSUE #1265: mapping validation error: key not found: nil (subject mapping)
## Backtrace

    line 88 of [PROJECT_ROOT]/app/services/cocina/from_fedora/descriptive/subject.rb: fetch
    line 88 of [PROJECT_ROOT]/app/services/cocina/from_fedora/descriptive/subject.rb: simple_item
    line 38 of [PROJECT_ROOT]/app/services/cocina/from_fedora/descriptive/subject.rb: block in build

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50568/faults/69242449)

### PR DESCRIPTION
**Pull request by ndushay**
## Why was this change made?

Fixes #1265 

Also updates references to mapping specification for xit statements.

## How was this change tested?

Was able to reproduce the error locally with new unit test, and the fix addressed it.

### CODE REVIEW

File: spec/services/cocina/from_fedora/descriptive/subject_spec.rb [hunk 1]
```diff
@@ -524,7 +527,32 @@
     end
 
     context 'with a name-title subject with additional terms including genre subdivision, authority for terms' do
-      xit 'TODO https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_subject.txt#L429'
+      xit 'TODO https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_subject.txt#L507'
+    end
+
+    context 'without name type' do
```
Comment (jcoyne) [inline spec/services/cocina/from_fedora/descriptive/subject_spec.rb:533]: Did you run this by @arcadiafalcone?  Did she agree that this is not a data error? Does an example need to be added into https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/mods_cocina_mappings/mods_to_cocina_subject.txt?

**Review by jcoyne — CHANGES_REQUESTED** [review]
After talking with Arcadia this sounds like a data error, so maybe we shouldn't apply this change.

**Comment by ndushay** [comment]
I am closing this PR, as you were on top of spotting this as a data error rather than a mapping error!   Thank you.

**Comment by ndushay** [comment]
Hrmm - I need to look at more examples -- it may be the one I chose to use as a spec was a data error but I don't think they all are.

**Comment by ndushay** [comment]
@jcoyne fixed the example in the spec to be data that has the problem, but isn't a subject masquerading as a name.

File: spec/services/cocina/from_fedora/descriptive/subject_spec.rb [hunk 2]
```diff
@@ -524,7 +527,34 @@
...
+      let(:xml) do
+        <<~XML
+          <subject authority="naf" authorityURI="http://id.loc.gov/authorities/names" valueURI="http://id.loc.gov/authorities/names/n81070667">
+            <name>
```
Comment (jcoyne) [inline spec/services/cocina/from_fedora/descriptive/subject_spec.rb:537]: Have we asked @arcadiafalcone if this shouldn't have `type="organization"` for this to be valid?

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: spec/services/cocina/from_fedora/descriptive/subject_spec.rb (hunk 2 above)
Comment (ndushay) [reply spec/services/cocina/from_fedora/descriptive/subject_spec.rb:537]: nope, I haven't talked to @arcadiafalcone .  We clearly have data like this, tho.  JLitt trapped 55 errors in his random sample ...

This fix avoids errors ... but whether it also needs to notify honeybadger for bad data ... I couldn't say.

**Comment by ndushay** [comment]
@jcoyne ready for re-review

File: spec/services/cocina/from_fedora/descriptive/subject_spec.rb (hunk 2 above)
Comment (justinlittman) [reply spec/services/cocina/from_fedora/descriptive/subject_spec.rb:537]: From @arcadiafalcone:
> ideally type="personal" would be present, but it's not required. i would like to remediate these, but it's valid mods to not have it.

So perhaps we should HB alert when no type?

Comment (arcadiafalcone) [reply spec/services/cocina/from_fedora/descriptive/subject_spec.rb:537]: Yes, alert for it but let it pass. 64 out of 373 nil_key errors I analyzed were bad data for reasons other than the missing type, and the rest were just missing the attribute. Missing the type doesn't make the records invalid MODS, but it will cause problems generating data in other schemas down the line and can be a symptom of something else wrong with the data.

**Review by jcoyne — APPROVED** [review]

**Review by ndushay — COMMENTED** [review]
Just pushed commit that alerts honeybadger when subject name has no type attribute.

File: spec/services/cocina/from_fedora/descriptive/subject_spec.rb (hunk 2 above)
Comment (ndushay) [reply spec/services/cocina/from_fedora/descriptive/subject_spec.rb:541]: Just pushed commit that alerts honeybadger when subject name has no type attribute.

**Comment by ndushay** [comment]
@jcoyne @justinlittman this now alerts Honeybadger when there is no type attribute on a name subject.

**Review by jcoyne — APPROVED** [review]

**Comment by justinlittman** [comment]
Verified that this reduces errors.
