### PR TITLE
do not error out on duplicate tag creation

### LINKED ISSUE #841: Allow creating a tag that already exists
ETDs does this and then fails when it tries to create the same tag the second time.

### PR DESCRIPTION
**Pull request by peetucket**
## Why was this change made?

fixes #841 

## Was the API documentation (openapi.yml) updated?

n/a

## Does this change affect how this application integrates with other services?
If so, please confirm change was tested on stage and/or test added to sul-dlss/infrastructure-integration-test.

### CODE REVIEW

**Comment by peetucket** [comment]
I'm not sure the test I altered is really substantial due to the mocking.  It would be nice to confirm the number of tags being created for example.

File: app/services/administrative_tags.rb [hunk 1]
```diff
@@ -90,13 +90,12 @@ def project
   # @param tags [Array<String>] a non-empty array of tags (strings)
   # @param replace [Boolean] replace current tags? default: false
   # @return [Array<AdministrativeTag>]
-  # @raise [ActiveRecord::RecordInvalid] if any druid/tag rows are duplicates
```
Comment (mjgiarlo) [inline app/services/administrative_tags.rb:93]: @peetucket Yanked this line out too since I don't believe we'll see it anymore.

File: spec/services/administrative_tags_spec.rb [hunk 2]
```diff
@@ -3,8 +3,7 @@
 require 'rails_helper'
 
 RSpec.describe AdministrativeTags do
-  let(:item_with_db_tags) { Dor::Item.new(pid: 'druid:aa123bb7890') }
-  let(:item_without_db_tags) { Dor::Item.new(pid: 'druid:bc234dg8901') }
+  let(:item) { Dor::Item.new(pid: 'druid:aa123bb7890') }
```
Comment (mjgiarlo) [inline spec/services/administrative_tags_spec.rb:6]: I should have renamed this variable to the simpler `item` when I removed the db migration code. Took the opportunity to do that now.

File: spec/services/administrative_tags_spec.rb [hunk 3]
```diff
@@ -79,159 +78,152 @@
...
 
       it 'returns an empty array' do
-        expect(described_class.project(item: item_with_db_tags)).to eq([])
+        expect(described_class.project(item: item)).to eq([])
       end
     end
   end
 
   describe '#create' do
-    before do
```
Comment (mjgiarlo) [inline spec/services/administrative_tags_spec.rb:165]: I... can't remember why I avoided manipulating the database before. Seems like the tests are better when we *do* manipulate the database. See the improved tests below.

Comment (peetucket) [reply spec/services/administrative_tags_spec.rb:165]: agreed, confirming the database changes is a nice way to confirm the expected behavior

**Comment by mjgiarlo** [comment]
@peetucket :speech_balloon: 
> I'm not sure the test I altered is really substantial due to the mocking. It would be nice to confirm the number of tags being created for example.

Agreed!
