### PR TITLE
Validate constituents before creating virtual object

### LINKED ISSUE #365: Validate all children before adding as constituents
Validate all children early before touching any objects and fail fast if any children can't be combined.

Blocks https://github.com/sul-dlss/argo/issues/1463

### PR DESCRIPTION
**Pull request by mjgiarlo**
Fixes #365 

Includes:
* Add `ItemQueryService.validate_combinable_items`. This new class method takes an array of druids and makes sure each is combinable. If any are not, a hash of errors is created and returned.
* Validate all items to be combined before modifying any of them.
* Raise exception from objects controller when constituent service raises.

### CODE REVIEW

File: app/services/item_query_service.rb [hunk 1]
```diff
@@ -11,6 +11,20 @@ def initialize(id:, item_relation: default_item_relation)
 
   delegate :allows_modification?, to: :item
 
+  # @param [Array] druids a list of druids
+  # @raises [RuntimeError] if any items are dark, citation_only, or not modifiable
```
Comment (jcoyne) [inline app/services/item_query_service.rb]: I don’t think this raises

File: app/services/constituent_service.rb [hunk 2]
```diff
@@ -15,7 +17,12 @@ def initialize(parent_druid:)
   # Typically this is only called one time (with a list of all the pids) because
   # subsequent calls will erase the previous changes.
   # @param [Array<String>] child_druids the identifiers of the child objects
+  # @raises NotCombinableError if validation of parent and child objects returns errors
```
Comment (jcoyne) [inline app/services/constituent_service.rb]: Could this return errors rather than raising an exception?

File: app/services/item_query_service.rb [hunk 3]
```diff
@@ -11,6 +11,20 @@ def initialize(id:, item_relation: default_item_relation)
...
+  def self.validate_combinable_items(druids)
+    errors = {}
+
+    druids.each do |druid|
+      find_combinable_item(druid)
+    rescue RuntimeError => e
```
Comment (jcoyne) [inline app/services/item_query_service.rb]: RuntimeError seems a bit broad.  Can we update find_combinable_item to raise a custom `UncombinableItemError`?

File: app/services/item_query_service.rb (hunk 1 above)
Comment (mjgiarlo) [reply app/services/item_query_service.rb]: It does not. This was from a prior implementation I worked on. Removing.

File: app/services/constituent_service.rb (hunk 2 above)
Comment (mjgiarlo) [reply app/services/constituent_service.rb]: Done.

File: app/services/item_query_service.rb (hunk 3 above)
Comment (mjgiarlo) [reply app/services/item_query_service.rb]: Done.

**Comment by mjgiarlo** [comment]
@jcoyne 	this is ready for another look now. Thanks for the review!
