### PR TITLE
Prevent indexing the same repository object concurrently to avoid rac…

### LINKED ISSUE #5231: Indexing is not keeping up with accessioning
The indexing statuses in Argo have been falling behind lately and I'm guessing the problem is the indexer itself is falling behind or failing to index as items complete accessioning.

As I write this issue, the Argo workflow grid shows 11 items waiting at the start of the accessionWF, but most of these items have actually been accessioned, some almost a day ago. The same problem applies to the 6 items listed as "started" at end-accession.
Screenshot 2024-11-19 at 5 23 10 PM

The show page has the same problem, where the status line shows "In accessioning" but the workflow display shows all the steps are complete
Screenshot 2024-11-19 at 5 25 13 PM

Manually reindexing corrects the issue so it seems like the indexing status is getting dropped somewhere while accessioning runs. Without manual reindex, these items will have incorrect statuses until the rolling indexer comes along.

### PR DESCRIPTION
**Pull request by justinlittman**
…es to commit solr record.

closes #5231

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

### CODE REVIEW

File: app/services/redis_lock.rb [hunk 1]
```diff
@@ -0,0 +1,54 @@
+# frozen_string_literal: true
+
+# A simple Redis-based lock implementation.
+# This is useful for ensuring that only one worker is processing a given job at a time.
+# Based on https://github.com/sul-dlss/preservation_catalog/blob/main/app/jobs/concerns/unique_job.rb
+class RedisLock
+  # @param [String] key the key to lock
+  # @param [Integer] lock_timeout the number of seconds before the lock expires
+  # @return [Boolean] true if the lock can be acquired
+  def self.lock(key:, lock_timeout:)
```
Comment (justinlittman) [inline app/services/redis_lock.rb:10]: There's really no good way to test this class.

**Review by aaron-collier — APPROVED** [review]
