### PR TITLE
Clear database connection after shelving

### LINKED ISSUE #943: [dor-services-app/prod] ActiveRecord::StatementInvalid: PG::ConnectionBad: PQconsumeInput() could not receive data from server: Connection timed out
: BEGIN
## Backtrace

    line 8 of [PROJECT_ROOT]/app/services/event_factory.rb: create
    line 15 of [PROJECT_ROOT]/app/jobs/shelve_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50568/faults/61855749)

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?

To avoid a timed out connection.  Fixes #943 

## How was this change tested?

Test suite

## Which documentation and/or configurations were updated?
n/a

### CODE REVIEW

File: app/jobs/shelve_job.rb [hunk 1]
```diff
@@ -25,6 +25,10 @@ def perform(druid:, background_job_result:)
       # end
 
       ShelvingService.shelve(item)
+
+      # Shelving can take a long time and can cause the database connections to get stale.
+      # So reset to avoid: ActiveRecord::StatementInvalid: PG::ConnectionBad: PQconsumeInput() could not receive data from server: Connection timed out : BEGIN
```
Comment (jermnelson) [inline app/jobs/shelve_job.rb:30]: What about referencing ticket #943 instead of including the error in this comment?

Comment (jcoyne) [reply app/jobs/shelve_job.rb:30]: I think that makes things more difficult for the person reading the code, why make them switch contexts when I can just provide the background here.
