### PR TITLE
ObjectsController#show: handle all Cocina::Mapper.build exceptions as 422

### LINKED ISSUE #1284: when showing an item that has a descriptive conversion error, return an explanation
Return a 422 (or something else?) with a JSON-API formatted error, and above all, avoid returning a generic 500 error with no explanation

This will show a more helpful message in the workflow service.

### PR DESCRIPTION
**Pull request by jmartin-sul**
## Why was this change made?

Handle unexpected errors from `Cocina::Mapper.build` so that an informative 422 is returned (with a ~~backtrace filtered to dor-services-app code~~full backtrace because my first attempt at filtering was hacky and this seemed useful as-is).  This will hopefully help future `Cocina::Mapper` debugging.

closes #1284

* supported by a bit more hierarchy for `Cocina::Mapper` exceptions
* `ObjectsController#json_api_error`: param for optional meta field in JSON-API error
  * `#show`: use meta field for returning backtrace
* test the new functionality
* update openapi spec for new json api error field

## How was this change tested?

unit tests

## Which documentation and/or configurations were updated?

hopefully code comments and new test suffice

### CODE REVIEW

**Comment by jmartin-sul** [comment]
CI sussed out some brittle code, pushing a fix momentarily...

File: app/controllers/objects_controller.rb [hunk 1]
```diff
@@ -135,7 +140,9 @@ def json_api_error(status:, message:, title: nil)
                  'status': status_code.to_s,
                  'title': title || Rack::Utils::HTTP_STATUS_CODES[status_code],
                  'detail': message
-               }
+               }.tap do |h|
+                 h[:backtrace] = backtrace.join("\n") if backtrace
```
Comment (jcoyne) [inline app/controllers/objects_controller.rb:144]: This field is not compliant with JSON-API (see https://jsonapi.org/format/1.1/#error-objects) maybe push it into the `detail`.

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: app/controllers/objects_controller.rb (hunk 1 above)
Comment (jcoyne) [reply app/controllers/objects_controller.rb:144]: It looks like `meta` might be another option (but you should then add it to the openapi.yml.

**Comment by jmartin-sul** [comment]
ok @jcoyne, i switched to returning a more structured backtrace array wrapped in the `meta` field, cleaned up the test to take advantage of the structure, and attempted to update the openapi spec to match the change.  ready for another look, i think.

File: app/services/cocina/mapper.rb [hunk 2]
```diff
@@ -3,17 +3,24 @@
...
     # Raised when this object is missing a sourceID, so it can't be mapped to cocina.
-    class MissingSourceID < StandardError; end
+    class MissingSourceID < BuildError; end
 
     # Raised when assumptions about descMetadata are violated
-    class InvalidDescMetadata < StandardError; end
+    class InvalidDescMetadata < BuildError; end
+
+    # Raised on unexpected mapper failures, so .build errors can be rescued without rescuing all of StandardError
+    class UnexpectedBuildError < BuildError; end
```
Comment (jcoyne) [inline app/services/cocina/mapper.rb:23]: Why not just rescue StandardError, since you wrap all StandardErrors with this class?

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: app/services/cocina/mapper.rb (hunk 2 above)
Comment (jmartin-sul) [reply app/services/cocina/mapper.rb:23]: i didn't want to catch errors from either of the lines above `Cocina::Mapper.build` since the ticket seemed to be asking for handling of "descriptive conversion" which i read (maybe incorrectly?) as being about the `.build` call.

happy to simplify and just catch `StandardError`.

**Review by jcoyne — APPROVED** [review]
