### PR TITLE
Fixes missing authority for topic.

### LINKED ISSUE #1549: Missing subject authority
For druid:kc373zp2312:
```
Original node:
<subject authority="lcsh">
  <topic authority="lcsh" valueURI="http://id.loc.gov/authorities/subjects/sh2008101488">Computer industry--United States--History</topic>
</subject>
Best guess roundtripped node:
<subject authority="lcsh">
  <topic valueURI="http://id.loc.gov/authorities/subjects/sh2008101488">Computer industry--United States--History</topic>
</subject>
```

Notice the missing authority attribute for `<subject>`.

### PR DESCRIPTION
**Pull request by justinlittman**
closes #1549

## Why was this change made?
Topics should have authority attribute even if subject has authority.

## How was this change tested?
Unit, sdr-deploy

## Which documentation and/or configurations were updated?
NA

### CODE REVIEW

**Comment by justinlittman** [comment]
Before:
```
Status (n=100000):
  Success:   78246 (78.246%)
  Different: 21082 (21.082%)
  To Cocina error:     33 (0.033%)
  To Fedora error:     29 (0.029%)
  Missing:     610 (0.61%)
```

After:
```
Status (n=100000):
  Success:   78331 (78.331%)
  Different: 20997 (20.997%)
  To Cocina error:     33 (0.033%)
  To Fedora error:     29 (0.029%)
  Missing:     610 (0.61%)
```

File: app/services/cocina/to_fedora/descriptive/subject.rb [hunk 1]
```diff
@@ -151,13 +151,13 @@ def write_topic(subject)
 
         def topic_attributes_for(subject)
           {}.tap do |topic_attributes|
-            if subject.source&.uri
-              topic_attributes[:authority] = subject.source.code
-              topic_attributes[:authorityURI] = subject.source.uri
+            if subject.source&.uri || subject.uri
```
Comment (jcoyne) [inline app/services/cocina/to_fedora/descriptive/subject.rb:154]: Can you explain this to me?  Why are you checking for `subject.uri` if it's not used in this block?

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: app/services/cocina/to_fedora/descriptive/subject.rb (hunk 1 above)
Comment (jcoyne) [reply app/services/cocina/to_fedora/descriptive/subject.rb:154]: Maybe this would be more readable if written as:
`subject.source&.uri || subject.source&.code`

Comment (justinlittman) [reply app/services/cocina/to_fedora/descriptive/subject.rb:154]: The authority should be written if there is an authorityURI (subject.source.uri) or a valueURI (subject.uri). Let me see if I can make that clearer in the code.

Comment (jcoyne) [reply app/services/cocina/to_fedora/descriptive/subject.rb:154]: or possibly even just `if subject.source` ?

Comment (justinlittman) [reply app/services/cocina/to_fedora/descriptive/subject.rb]: OK. Disentangled a bit.

**Review by mjgiarlo — APPROVED** [review]

File: app/services/cocina/to_fedora/descriptive/subject.rb [hunk 2]
```diff
@@ -151,13 +151,11 @@ def write_topic(subject)
...
         def topic_attributes_for(subject)
           {}.tap do |topic_attributes|
-            if subject.source&.uri
-              topic_attributes[:authority] = subject.source.code
-              topic_attributes[:authorityURI] = subject.source.uri
-            end
-            topic_attributes[:encoding] = subject.encoding.code if subject.encoding
-            topic_attributes[:valueURI] = subject.uri if subject.uri
-          end
+            topic_attributes[:authority] = subject.source&.code if subject.source&.uri || subject.uri
```
Comment (jcoyne) [inline app/services/cocina/to_fedora/descriptive/subject.rb:154]: do we still need the trailing conditional? Would it work without `if subject.source&.uri || subject.uri`?

Comment (justinlittman) [reply app/services/cocina/to_fedora/descriptive/subject.rb:154]:
```
Failed examples:

rspec ./spec/services/cocina/to_fedora/descriptive/subject_spec.rb:163 # Cocina::ToFedora::Descriptive::Subject when it has a single-term topic subject with non-lcsh authority builds the xml
rspec ./spec/services/cocina/to_fedora/descriptive/subject_spec.rb:745 # Cocina::ToFedora::Descriptive::Subject when it has a musical genre as topic see it builds the xml
rspec ./spec/services/cocina/to_fedora/descriptive/subject_spec.rb:191 # Cocina::ToFedora::Descriptive::Subject when it has a single-term topic subject with authority but no valueURI builds the xml
```

**Review by jcoyne — APPROVED** [review]
