### PR TITLE
[HOLD] fix normalization of embargoMetadata

### LINKED ISSUE #3284: Embargo normalizer is over-enthusiastic
For example, druid:bw190bf2187:
```
Original XML for embargoMetadata:
<?xml version="1.0"?>
<embargoMetadata>
  <status>embargoed</status>
  <releaseDate>2022-05-06T00:00:00Z</releaseDate>
  <twentyPctVisibilityStatus/>
  <twentyPctVisibilityReleaseDate/>
  <releaseAccess>
    <access type="discover">
      <machine>
        <world/>
      </machine>
    </access>
    <access type="read">
      <machine>
        <world/>
      </machine>
    </access>
  </releaseAccess>
</embargoMetadata>


Normalized original XML for embargoMetadata:
<?xml version="1.0" encoding="UTF-8"?>
<embargoMetadata>
  <status>embargoed</status>
  <releaseDate>2022-05-06T00:00:00Z</releaseDate>
</embargoMetadata>
```

`<releaseAccess>` should NOT be deleted in normalization.

### PR DESCRIPTION
**Pull request by peetucket**
## Why was this change made?

Fixes #3284 - do not blindly remove all `<releaseAccess>` nodes, as some of them may contain important empty nodes.  Test for this was added in #3301 and now passes.

HOLD: re-running validate cocina tests

## How was this change tested?

Existing tests.

### CODE REVIEW

File: app/services/cocina/normalizers/base.rb [hunk 1]
```diff
@@ -7,23 +7,6 @@ module Base
...
-           start_node.attributes.size.zero? &&
-           start_node.name != 'etal'
-          parent = start_node.parent
-          start_node.remove
-          remove_empty_elements(parent) # need to call again after child has been deleted
-        else
-          start_node.element_children.each { |e| remove_empty_elements(e) }
-        end
-      end
     end
```
Comment (peetucket) [inline app/services/cocina/normalizers/base.rb:10]: This method was moved out of Base and to the MODS normalizer, as it is specific to MODs (see `etal`) and is only used by that single normalizer.

File: app/services/cocina/normalizers/mods_normalizer.rb [hunk 2]
```diff
@@ -73,6 +73,23 @@ def normalize_purl
...
+           start_node.name != 'etal'
+          parent = start_node.parent
+          start_node.remove
+          remove_empty_elements(parent) # need to call again after child has been deleted
+        else
+          start_node.element_children.each { |e| remove_empty_elements(e) }
+        end
+      end
+
       def normalize_default_namespace
```
Comment (peetucket) [inline app/services/cocina/normalizers/mods_normalizer.rb:93]: just moved method from base to the class where it used

File: app/services/cocina/normalizers/embargo_normalizer.rb [hunk 3]
```diff
@@ -31,7 +32,9 @@ def normalize
       attr_reader :ng_xml
 
       def normalize_empty
-        ng_xml.root.xpath('*[not(text())][not(@*)]').each(&:remove)
+        ng_xml.root.xpath('*[not(text())][not(@*)]').each do |node|
+          node.remove unless node.name == 'releaseAccess' && !node.children.empty?
+        end
         ng_xml.root.remove if ng_xml.root.xpath('*').empty?
```
Comment (peetucket) [inline app/services/cocina/normalizers/embargo_normalizer.rb:38]: this was the single point of overeagerness according to the current tests, making it more generic caused other test failures

**Review by justinlittman — APPROVED** [review]
Can you run before/after on sdr-deploy to make sure that causes no harm?

**Comment by peetucket** [comment]
> Can you run before/after on sdr-deploy to make sure that causes no harm?

Yup, thanks for the reminder.  Will do that now and then post results.

**Comment by peetucket** [comment]
Running on this PR:

```
[deploy@sdr-deploy dor-services-app]$ bin/validate-cocina-roundtrip -s 100000 -i druids.testbed.txt -f
Status (n=100000; not using Missing for success/different/error stats):
  Success:   97151 (97.231%)
  Different: 2754 (2.756%)
  Mapping error:     13 (0.013%)
  Create error:     0 (0.0%)
  Normalization error:     0 (0.0%)
  Missing from cache:     0 (0.0%)
  Unmapped:     0 (0.0%)
  Expected unmapped:     82 (0.082%)
  Bad cache:     0 (0.0%)
```

Running on main:

```
[deploy@sdr-deploy dor-services-app]$ bin/validate-cocina-roundtrip -s 100000 -i druids.testbed.txt -f

```

**Comment by peetucket** [comment]
> Can you run before/after on sdr-deploy to make sure that causes no harm?

There is no change in the roundtrip results with this PR.  I think this is expected (i.e. it didn't get better, but it didn't get worse).

**Comment by peetucket** [comment]
Running on this PR:

```
[deploy@sdr-deploy dor-services-app]$ bin/validate-cocina-roundtrip -s 100000 -i druids.testbed.txt -f
Status (n=100000; not using Missing for success/different/error stats):
  Success:   88514 (88.587%)
  Different: 2741 (2.743%)
  Mapping error:     13 (0.013%)
  Create error:     0 (0.0%)
  Normalization error:     8650 (8.657%)
  Missing from cache:     0 (0.0%)
  Unmapped:     0 (0.0%)
  Expected unmapped:     82 (0.082%)
  Bad cache:     0 (0.0%)
```


Running on main:

```
[deploy@sdr-deploy dor-services-app]$ bin/validate-cocina-roundtrip -s 100000 -i druids.testbed.txt -f
Status (n=100000; not using Missing for success/different/error stats):
  Success:   97152 (97.232%)
  Different: 2753 (2.755%)
  Mapping error:     13 (0.013%)
  Create error:     0 (0.0%)
  Normalization error:     0 (0.0%)
  Missing from cache:     0 (0.0%)
  Unmapped:     0 (0.0%)
  Expected unmapped:     82 (0.082%)
  Bad cache:     0 (0.0%)
```

**Comment by justinlittman** [comment]
@peetucket Please fixup the commits and then good to merge.

**Comment by peetucket** [comment]
squashed the commits, but what do you make the normalization error rate on this PR being so high compared to main?

**Comment by peetucket** [comment]
Eliminated the mapping error by guarding against nil -- now have a tiny increase in success with no further errors.

**Comment by jcoyne** [comment]
Is there a reason this is marked as "HOLD"?

**Comment by justinlittman** [comment]
Yes, we had some problems to iron out. However, now done.
