### PR TITLE
Handle Hydrus APOs with no descriptive metadata.

### LINKED ISSUE #3553: Error: undefined method `at' for nil:NilClass
```
Druid: druid:fr539cg7287

Error: undefined method `at' for nil:NilClass

Backtrace:
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/mapper.rb:53:in `rescue in build'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/mapper.rb:39:in `build'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/mapper.rb:28:in `build'
bin/validate-cocina-roundtrip:215:in `validate_druid'
bin/validate-cocina-roundtrip:291:in `block in <main>'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:515:in `call_with_index'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:485:in `process_incoming_jobs'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:465:in `block in worker'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:456:in `fork'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:456:in `worker'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:447:in `block in create_workers'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `each'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `each_with_index'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `create_workers'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:386:in `work_in_processes'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:289:in `map'
bin/validate-cocina-roundtrip:290:in `<main>'

Cause:
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/descriptive.rb:78:in `check_version'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/descriptive.rb:31:in `props'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/descriptive.rb:17:in `props'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/dro.rb:66:in `block in props'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/dro.rb:64:in `tap'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/dro.rb:64:in `props'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/dro.rb:11:in `props'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/mapper.rb:42:in `build'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/mapper.rb:28:in `build'
bin/validate-cocina-roundtrip:215:in `validate_druid'
bin/validate-cocina-roundtrip:291:in `block in <main>'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:515:in `call_with_index'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:485:in `process_incoming_jobs'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:465:in `block in worker'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:456:in `fork'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:456:in `worker'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:447:in `block in create_workers'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `each'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `each_with_index'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `create_workers'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:386:in `work_in_processes'
/opt/app/deploy/sdr-deploy/shared/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:289:in `map'
bin/validate-cocina-roundtrip:290:in `<main>'
```

### PR DESCRIPTION
**Pull request by justinlittman**
closes #3553

## Why was this change made? 🤔
Avoid normalizer error.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

Before:
```
Status (n=100000; not using Missing for success/different/error stats):
  Success:   99795 (99.877%)
  Different: 123 (0.123%)
  Mapping error:     0 (0.0%)
  Create error:     0 (0.0%)
  Normalization error:     0 (0.0%)
  Missing from cache:     0 (0.0%)
  Unmapped:     0 (0.0%)
  Expected unmapped:     82 (0.082%)
  Bad cache:     0 (0.0%)
  Validate error:     0 (0.0%)
```

After:
```
Status (n=100000; not using Missing for success/different/error stats):
  Success:   99795 (99.877%)
  Different: 123 (0.123%)
  Mapping error:     0 (0.0%)
  Create error:     0 (0.0%)
  Normalization error:     0 (0.0%)
  Missing from cache:     0 (0.0%)
  Unmapped:     0 (0.0%)
  Expected unmapped:     82 (0.082%)
  Bad cache:     0 (0.0%)
  Validate error:     0 (0.0%)
```

This was also tested locally with some know problems.

### CODE REVIEW

**Review by ndushay — APPROVED** [review]

File: app/services/cocina/from_fedora/descriptive.rb [hunk 1]
```diff
@@ -27,6 +27,8 @@ def initialize(title_builder:, mods:, druid:, notifier:)
       # @return [Hash] a hash that can be mapped to a cocina descriptive model
       # @raises [Cocina::Mapper::InvalidDescMetadata] if some assumption about descMetadata is violated
       def props
+        return nil if ng_xml.root.nil?
```
Comment (jcoyne) [inline app/services/cocina/from_fedora/descriptive.rb:30]: Why is this PR about contentMetadata, but this change is affecting descMetadata?

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: app/services/cocina/from_fedora/descriptive.rb (hunk 1 above)
Comment (ndushay) [reply app/services/cocina/from_fedora/descriptive.rb:30]: That is a most excellent question.

Comment (ndushay) [reply app/services/cocina/from_fedora/descriptive.rb:30]: Looks like PR title is wrong:  https://github.com/sul-dlss/dor-services-app/issues/3553

```
Cause:
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/descriptive.rb:78:in `check_version'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/descriptive.rb:31:in `props'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/descriptive.rb:17:in `props'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/dro.rb:66:in `block in props'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/dro.rb:64:in `tap'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/dro.rb:64:in `props'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/from_fedora/dro.rb:11:in `props'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/mapper.rb:42:in `build'
/opt/app/deploy/jlit/dor-services-app/app/services/cocina/mapper.rb:28:in `build'
bin/validate-cocina-roundtrip:215:in `validate_druid'
```

Comment (ndushay) [reply app/services/cocina/from_fedora/descriptive.rb:30]: I changed the title.

Comment (justinlittman) [reply app/services/cocina/from_fedora/descriptive.rb:30]: I changed the commit message.

**Review by jcoyne — APPROVED** [review]
