### PR TITLE
Compare the opaque lock value for active-record based models

### LINKED ISSUE #3805: [dor-services-app/qa] CocinaObjectStore::StaleLockError: Expected lock of 0 but received 401a58a630f3ab3c2d955bbbff494e9e.
## Backtrace

    line 264 of [PROJECT_ROOT]/app/services/cocina_object_store.rb: ar_check_lock
    line 240 of [PROJECT_ROOT]/app/services/cocina_object_store.rb: cocina_to_ar_save
    line 96 of [PROJECT_ROOT]/app/services/cocina_object_store.rb: save

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50568/faults/84804668)

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made? 🤔

Fixes #3805

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, including data writes to shared file systems, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

### CODE REVIEW

**Review by jmartin-sul — APPROVED** [review]

File: spec/services/cocina_object_store_spec.rb [hunk 1]
```diff
@@ -706,9 +706,9 @@
 
         context 'when checking lock succeeds' do
           let(:ar_cocina_object) { create(:dro) }
-
+          let(:lock) { '7d6d3ed4f76c412ae5bf17adbed768ac' }
```
Comment (jmartin-sul) [inline spec/services/cocina_object_store_spec.rb:709]: circle is complaining that the test is failing with:

```
Failure/Error: raise StaleLockError, "Expected lock of #{lock} but received #{cocina_object.lock}."

CocinaObjectStore::StaleLockError:
  Expected lock of 64e8320d19d62ddb73c501276c5655cf but received 7d6d3ed4f76c412ae5bf17adbed768ac.
./app/services/cocina_object_store.rb:265:in `ar_check_lock'
./app/services/cocina_object_store.rb:240:in `cocina_to_ar_save'
./spec/services/cocina_object_store_spec.rb:719:in `block (6 levels) in <top (required)>'
```

**Review by jmartin-sul — APPROVED** [review]
