### PR TITLE
search all url nodes for primary designation when normalizing PURLs

### LINKED ISSUE #1518: Mapping error: PURL mistakenly has primary display usage
PURL should only have `usage="primary display"` when there is no other `<url>` with `usage="primary display"` .

See, for example, druid:cy979mw6316.

This is wrong:
```
<location>
  <physicalLocation>Stanford University Libraries</physicalLocation>
  <url usage="primary display">http://infoweb.newsbank.com/?db=SERIAL</url>
  <url>http://web.lexis-nexis.com/congcomp/form/cong/s_pubadvanced.html?srcboxes=SSMaps&amp;srcboxes=SerialSet</url>
  <url>http://purl.access.gpo.gov/GPO/LPS839</url>
  <url usage="primary display">http://purl.stanford.edu/cy979mw6316</url>
</location>
```

### PR DESCRIPTION
**Pull request by peetucket**
## Why was this change made?

Fixes #1518 (incorrect PURL normalization with primary usage designation).  Did some refactoring to make this more clear (hopefully)

## How was this change tested?

Added new unit test

### CODE REVIEW

File: db/structure.sql [hunk 1]
```diff
@@ -318,3 +318,5 @@ INSERT INTO "schema_migrations" (version) VALUES
 ('20200507202950'),
 ('20200507224637'),
 ('20200521153735');
+
```
Comment (mjgiarlo) [inline db/structure.sql:321]: Cruft?

**Review by mjgiarlo — APPROVED** [review]
Maybe some DB cruft but :+1:

File: db/structure.sql (hunk 1 above)
Comment (peetucket) [reply db/structure.sql:321]: yeah, not sure where that came from, i had to bring my environment up to date and this got changed and committed by mistake -- i'll just revert his file back to what it was
