### PR TITLE
Fix mapping of life dates on name part subelements of title

### LINKED ISSUE #1234: cocina mapping error: key not found: "life dates"
seen on stage.
```
druid:fw124bx4247 error. key not found: "life dates"
```

See Cocina model in https://argo-stage.stanford.edu/view/druid:fw124bx4247. Any structured values including the type `'life dates'` is not mapping. Fix `ToFedora` mapping in dor-services-app.

### PR DESCRIPTION
**Pull request by aaron-collier**
## Why was this change made?

Fixes #1234 

## How was this change tested?

Adds a unit test for title with name part subelements.

## Which documentation and/or configurations were updated?

N/A

### CODE REVIEW

File: app/services/cocina/from_fedora/descriptive/titles.rb [hunk 1]
```diff
@@ -10,11 +10,17 @@ class Titles
...
+          'partName' => 'part name',
+          'date' => 'life dates',
+          'given' => 'forename',
+          'family' => 'surname',
+          'uniform title' => 'title'
         }.freeze
 
         PERSON_TYPE = 'person'
 
+        NAME_TYPES = ['person', 'forename', 'surname', 'life dates'].freeze
```
Comment (jcoyne) [inline app/services/cocina/from_fedora/descriptive/titles.rb:22]: Should this be moved to the `to_fedora` class, where it's used?

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: app/services/cocina/to_fedora/descriptive/title.rb [hunk 2]
```diff
@@ -61,34 +63,96 @@ def write_parallel(title, alt_rep_group:)
...
+        end
+
+        def names
+          return unless components[true]
+
+          @names ||= components[true].group_by { |name| FromFedora::Descriptive::Titles::PERSON_TYPE == name.type }
+        end
+
+        def basic_names
+          return unless names[false]
```
Comment (jcoyne) [inline app/services/cocina/to_fedora/descriptive/title.rb:115]: Is this conditional necessary?

File: app/services/cocina/to_fedora/descriptive/title.rb [hunk 3]
```diff
@@ -61,34 +63,96 @@ def write_parallel(title, alt_rep_group:)
...
+
+          names[false]
+        end
+
+        def name_with_authority
+          return unless names[true]
+
+          names[true].first
```
Comment (jcoyne) [inline app/services/cocina/to_fedora/descriptive/title.rb:123]:
```suggestion
          Array(names[true]).first
```

File: app/services/cocina/to_fedora/descriptive/title.rb [hunk 4]
```diff
@@ -61,34 +63,96 @@ def write_parallel(title, alt_rep_group:)
...
+            attrs[:authority] = name_with_authority.source.code if name_with_authority&.source&.code
+          end
+        end
+
+        def sturctured_titles
+          components[false]
+        end
+
+        def name_title_group
+          return nil unless names
```
Comment (jcoyne) [inline app/services/cocina/to_fedora/descriptive/title.rb:142]:
```suggestion
          return unless names
```

File: app/services/cocina/to_fedora/descriptive/title.rb [hunk 5]
```diff
@@ -61,34 +63,96 @@ def write_parallel(title, alt_rep_group:)
...
+          name_attr = {}
+          name_attr[:type] = name_type if name_type
+          xml.namePart name[:value], name_attr
+        end
+
         def with_uri_info(cocina, xml_attrs)
-          xml_attrs[:valueURI] = cocina.uri
-          xml_attrs[:authorityURI] = cocina.source&.uri
-          xml_attrs[:authority] = cocina.source&.code
+          if cocina
```
Comment (jcoyne) [inline app/services/cocina/to_fedora/descriptive/title.rb:96]: Is this conditional necessary? The only thing passed here is `title` and I don't think it could ever be nil.

**Review by jcoyne — CHANGES_REQUESTED** [review]

**Review by jcoyne — APPROVED** [review]
