### PR TITLE
Handle missing coordinates.

### LINKED ISSUE #1184: Cocina Mapping Error: undefined method `text' for nil:NilClass
```
druid:rt706cv5800 error. undefined method `text' for nil:NilClass
```

### PR DESCRIPTION
**Pull request by justinlittman**
closes #1184

## Why was this change made?
To handle cases in which coordinates is missing from a geo subject.

## How was this change tested?
Unit

## Which documentation and/or configurations were updated?
NA

### CODE REVIEW

File: spec/services/cocina/from_fedora/descriptive/subject_spec.rb [hunk 1]
```diff
@@ -584,6 +584,23 @@
...
+          <cartographics>
+            <scale>1:22,000,000</scale>
+            <projection>Conic proj</projection>
+          </cartographics>
+        </subject>
+      XML
+    end
+
+    it 'builds the cocina data structure' do
+      expect(build).to eq []
```
Comment (jcoyne) [inline spec/services/cocina/from_fedora/descriptive/subject_spec.rb:600]: This would result in data loss? Shoudn't it transform the data it has at least?

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: spec/services/cocina/from_fedora/descriptive/subject_spec.rb (hunk 1 above)
Comment (jcoyne) [reply spec/services/cocina/from_fedora/descriptive/subject_spec.rb:600]: Ah, those are in form. Nothing is lost.

**Review by jcoyne — APPROVED** [review]

**Comment by jcoyne** [comment]
Please rebase.
