### PR TITLE
Fixes nameTitleGroup handling.

### LINKED ISSUE #1597: Name mapping multiplication
For druid:pt090nw8804:

Original:
```
<name type="personal" usage="primary" nameTitleGroup="1">
    <namePart>Staniszkis, Jadwiga</namePart>
  </name>
```

Roundtripped:
```
<name type="personal" nameTitleGroup="1">
    <namePart>Staniszkis, Jadwiga</namePart>
  </name>
  <name type="personal" usage="primary">
    <namePart>Staniszkis, Jadwiga</namePart>
  </name>
```

### PR DESCRIPTION
**Pull request by justinlittman**
closes #1597

## Why was this change made?
Ahhhh!!!

## How was this change tested?
Unit, sdr-deploy

## Which documentation and/or configurations were updated?
NA

### CODE REVIEW

**Comment by justinlittman** [comment]
Before:
```
Status (n=100000):
  Success:   83518 (83.518%)
  Different: 15815 (15.815%)
  To Cocina error:     33 (0.033%)
  To Fedora error:     24 (0.024%)
  Missing:     610 (0.61%)
```

After:
```
Status (n=100000):
  Success:   84480 (84.48%)
  Different: 14853 (14.853%)
  To Cocina error:     33 (0.033%)
  To Fedora error:     24 (0.024%)
  Missing:     610 (0.61%)
```

File: app/services/cocina/from_fedora/descriptive/name_builder.rb [hunk 1]
```diff
@@ -0,0 +1,190 @@
+# frozen_string_literal: true
+
+# rubocop:disable Metrics/ClassLength
+module Cocina
+  module FromFedora
+    class Descriptive
+      # Maps a name
+      class NameBuilder
```
Comment (jcoyne) [inline app/services/cocina/from_fedora/descriptive/name_builder.rb:8]: 👏

**Review by jcoyne — APPROVED** [review]
