### PR TITLE
Fixed multi-term topic subject with authority for terms test.

### LINKED ISSUE #1962: Fix "Multi-term topic subject with authority for terms" test
In `subject_topic_spec.rb`.

### PR DESCRIPTION
**Pull request by justinlittman**
closes #1962

## Why was this change made?
Tests want to be green.

## How was this change tested?
Unit, sdr-deploy

## Which documentation and/or configurations were updated?
NA

### CODE REVIEW

**Comment by justinlittman** [comment]
Example changes were approved by @arcadiafalcone via slack.

**Comment by justinlittman** [comment]
Before:
```
Status (n=100000):
  Success:   98169 (98.169%)
  Different: 1282 (1.282%)
  To Cocina error:     18 (0.018%)
  To Fedora error:     0 (0.0%)
  Missing:     531 (0.531%)
```

After:
```
Status (n=100000):
  Success:   98193 (98.193%)
  Different: 1258 (1.258%)
  To Cocina error:     18 (0.018%)
  To Fedora error:     0 (0.0%)
  Missing:     531 (0.531%)
```

**Comment by justinlittman** [comment]
Review by @arcadiafalcone + Infra dev please.

File: app/services/cocina/from_fedora/descriptive/subject.rb [hunk 1]
```diff
@@ -123,9 +124,18 @@ def geo_code_and_terms(node_set, attrs)
           attrs.presence
         end
 
+        def adjust_source(attrs)
+          attrs.delete(:source) if remove_source?(attrs)
+
+          # If attr has source, add to all values that have valueURI but no source.
+          attrs[:structuredValue].each do |value|
+            value[:source] = attrs[:source] if attrs[:source] && !value[:source] && value[:uri]
```
Comment (jcoyne) [inline app/services/cocina/from_fedora/descriptive/subject.rb:132]: could this be `value[:source] ||=  attrs[:source] if attrs[:source] && value[:uri]` ?

File: app/services/cocina/mods_normalizer.rb [hunk 2]
```diff
@@ -6,6 +6,8 @@ module Cocina
   class ModsNormalizer
     MODS_NS = Cocina::FromFedora::Descriptive::DESC_METADATA_NS
 
+    SUBJECT_CHILDREN_NAMES = 'mods:name|mods:topic|mods:geographic|mods:genre|mods:temporal'
```
Comment (arcadiafalcone) [inline app/services/cocina/mods_normalizer.rb:9]: Is this supposed to include all possible subject subelements? There are several more not on this list.

File: app/services/cocina/mods_normalizer.rb [hunk 3]
```diff
@@ -97,32 +102,103 @@ def normalize_authority_uris
...
     end
 
-    # rubocop:disable Metrics/CyclomaticComplexity
     # rubocop:disable Metrics/PerceivedComplexity
-    # rubocop:disable Metrics/AbcSize
+    # rubocop:disable Metrics/CyclomaticComplexity
     def normalize_subject
-      ng_xml.root.xpath('//mods:subject[count(mods:name|mods:topic|mods:geographic) = 1 and count(mods:*) = 1]', mods: MODS_NS).each do |subject_node|
-        child_node = subject_node.xpath('mods:*', mods: MODS_NS).first
+      ng_xml.root.xpath("//mods:subject[count(#{SUBJECT_CHILDREN_NAMES}) >= 1 and count(mods:*) = count(#{SUBJECT_CHILDREN_NAMES})]", mods: MODS_NS).each do |subject_node|
```
Comment (jcoyne) [inline app/services/cocina/mods_normalizer.rb:108]: Can you drop a comment here explaining what this is querying for?

File: app/services/cocina/mods_normalizer.rb [hunk 4]
```diff
@@ -97,32 +102,103 @@ def normalize_authority_uris
...
-          child_node[:valueURI] = subject_node[:valueURI] if subject_node[:valueURI] && !child_node[:valueURI]
+          add_valueURI(children_nodes, subject_node) if have_valueURI?(subject_node) && !have_valueURI?(children_nodes)
           subject_node.delete('valueURI')
-        elsif child_node[:authority] && subject_node[:authority] == child_node[:authority] && !(child_node[:authorityURI] || child_node[:valueURI])
-          child_node.delete('authority')
-        elsif subject_node[:authority] && !child_node[:authority] && (child_node[:authorityURI] || child_node[:valueURI])
-          child_node[:authority] = subject_node[:authority]
         end
+
+        next unless have_authority?(subject_node) \
```
Comment (jcoyne) [inline app/services/cocina/mods_normalizer.rb:123]: If you put the `&&` at the end of the lines then you don't need `\`s

File: app/services/cocina/mods_normalizer.rb [hunk 5]
```diff
@@ -97,32 +102,103 @@ def normalize_authority_uris
...
+
+        delete_authorityURI(subject_node)
+      end
+    end
+
+    def normalize_subject_children
+      ng_xml.root.xpath("//mods:subject[count(#{SUBJECT_CHILDREN_NAMES}) >= 1 and count(mods:*) = count(#{SUBJECT_CHILDREN_NAMES})]", mods: MODS_NS).each do |subject_node|
+        children_nodes = subject_node.xpath('mods:*', mods: MODS_NS)
+
+        if !have_authorityURI?(subject_node) \
```
Comment (jcoyne) [inline app/services/cocina/mods_normalizer.rb:137]: If you put the `&&` at the end of the lines then you don't need `\`s

File: app/services/cocina/mods_normalizer.rb [hunk 6]
```diff
@@ -97,32 +102,103 @@ def normalize_authority_uris
...
+          && !have_valueURI?(subject_node) \
+          && have_authority?(children_nodes) \
+          && have_same_authority?(children_nodes, subject_node) \
+          && !(have_authorityURI?(children_nodes) || have_valueURI?(children_nodes))
+          delete_authority(children_nodes)
+        end
+
+        next unless !have_authorityURI?(subject_node) \
```
Comment (jcoyne) [inline app/services/cocina/mods_normalizer.rb:145]: If you put the `&&` at the end of the lines then you don't need `\`s

File: app/services/cocina/mods_normalizer.rb [hunk 7]
```diff
@@ -97,32 +102,103 @@ def normalize_authority_uris
...
+    def have_valueURI?(nodes)
+      nodes_to_a(nodes).all? { |node| node[:valueURI] }
+    end
+
+    def add_valueURI(nodes, from_node)
+      nodes_to_a(nodes).each { |node| node[:valueURI] = from_node[:valueURI] }
+    end
+    # rubocop:enable Naming/MethodName
+
+    def nodes_to_a(nodes)
```
Comment (jcoyne) [inline app/services/cocina/mods_normalizer.rb:199]: What else are you expecting this to be other than a `Nokogiri::XML::NodeSet`?

File: spec/services/cocina/mapping/descriptive/mods/subject_spec.rb [hunk 8]
```diff
@@ -0,0 +1,68 @@
+# frozen_string_literal: true
+
+require 'rails_helper'
+
+RSpec.describe 'MODS subject topic <--> cocina mappings' do
+  describe 'Multi-term subject with authority for both set and terms' do
```
Comment (arcadiafalcone) [inline spec/services/cocina/mapping/descriptive/mods/subject_spec.rb:6]: I would add 'and URIs for terms' to distinguish between this case and when all three authority attributes are present at all levels.

File: app/services/cocina/to_fedora/descriptive/subject.rb [hunk 9]
```diff
@@ -108,18 +108,24 @@ def structured_attributes_for(subject, alt_rep_group: nil)
             displayLabel: subject.displayLabel
           }.tap do |attrs|
             if subject.source
+              # If all values in structuredValue have uri, then authority only.
               attrs[:authority] = authority_for(subject)
-              attrs[:authorityURI] = subject.source.uri
-            elsif all_same_authority?(subject.structuredValue)
-              attrs[:authority] = authority_for(subject.structuredValue.first)
+              attrs[:authorityURI] = subject.source.uri unless all_values_have_uri?(subject.structuredValue) && !subject.uri
```
Comment (jcoyne) [inline app/services/cocina/to_fedora/descriptive/subject.rb:113]: How about using `if !all_values_have_uri?(subject.structuredValue) || subject.url` instead.  That's less boolean logic to wrap ones head around.

File: app/services/cocina/mods_normalizer.rb (hunk 2 above)
Comment (jcoyne) [reply app/services/cocina/mods_normalizer.rb:9]: I was also wondering why this couldn't be `mods:*`?

File: spec/services/cocina/mapping/descriptive/mods/subject_spec.rb [hunk 10]
```diff
@@ -0,0 +1,68 @@
...
+            <temporal authority="lcsh" authorityURI="http://id.loc.gov/authorities/subjects/" valueURI="http://id.loc.gov/authorities/subjects/sh2002012475">19th century</temporal>
+          </subject>
+        XML
+      end
+
+      let(:cocina) do
+        {
+          subject: [
+            {
+              "structuredValue": [
```
Comment (arcadiafalcone) [inline spec/services/cocina/mapping/descriptive/mods/subject_spec.rb:33]: This is slightly different than the example we looked at before. In that example one subject subelement had a source and the other didn't. When the source is exactly the same for all parts of a `structuredValue`, it should be a sibling to the `structuredValue`. If one of the parts were e.g. a name, then the source would be at the part level because it is not the same for all parts.

File: spec/services/cocina/mapping/descriptive/mods/subject_topic_spec.rb [hunk 11]
```diff
@@ -257,43 +257,50 @@
...
-                value: 'Behavior',
-                type: 'topic',
-                uri: 'http://id.loc.gov/authorities/subjects/sj96004895'
+      let(:cocina) do
+        {
+          subject: [
+            {
+              structuredValue: [
+                {
+                  value: 'Cats',
```
Comment (arcadiafalcone) [inline spec/services/cocina/mapping/descriptive/mods/subject_topic_spec.rb:278]: Same as above - identical part source should be at subject level.

File: spec/services/cocina/mapping/descriptive/mods/subject_topic_spec.rb [hunk 12]
```diff
@@ -346,6 +353,58 @@
...
+      end
+
+      let(:roundtrip_mods) do
+        <<~XML
+          <subject authority="lcsh">
+            <topic authority="lcsh" valueURI="http://id.loc.gov/authorities/subjects/sh23456">Horses</topic>
+            <topic authority="lcsh" valueURI="http://id.loc.gov/authorities/subjects/sh34567">History</topic>
+          </subject>
+        XML
+      end
```
Comment (arcadiafalcone) [inline spec/services/cocina/mapping/descriptive/mods/subject_topic_spec.rb:374]: The roundtrip can be the same as the original.

File: app/services/cocina/from_fedora/descriptive/subject.rb (hunk 1 above)
Comment (justinlittman) [reply app/services/cocina/from_fedora/descriptive/subject.rb:132]: Yes. Fixed.

File: app/services/cocina/mods_normalizer.rb (hunk 4 above)
Comment (justinlittman) [reply app/services/cocina/mods_normalizer.rb:123]: Ahh ... thanks.

File: app/services/cocina/mods_normalizer.rb (hunk 7 above)
Comment (justinlittman) [reply app/services/cocina/mods_normalizer.rb:199]: A single node. Unfortunately, the usual `Array()` magic doesn't work with `NodeSet`, hence this helper method.

File: app/services/cocina/mods_normalizer.rb (hunk 2 above)
Comment (justinlittman) [reply app/services/cocina/mods_normalizer.rb:9]: At the end of the day, this needed to exclude subjects with `<cartographics>` children. That can be accomplished with `not(mods:cartographics)`, so `SUBJECT_CHILDREN_NAMES` will disappear.

And in testing, this reduced a single difference, so "yeah".

File: spec/services/cocina/mapping/descriptive/mods/subject_spec.rb (hunk 8 above)
Comment (justinlittman) [reply spec/services/cocina/mapping/descriptive/mods/subject_spec.rb:6]: Done.

File: app/services/cocina/to_fedora/descriptive/subject.rb (hunk 9 above)
Comment (justinlittman) [reply app/services/cocina/to_fedora/descriptive/subject.rb:113]: But less fun.

File: spec/services/cocina/mapping/descriptive/mods/subject_topic_spec.rb (hunk 12 above)
Comment (justinlittman) [reply spec/services/cocina/mapping/descriptive/mods/subject_topic_spec.rb:374]: Yes, but the round-trip is how we normalize it.

File: app/services/cocina/mods_normalizer.rb (hunk 7 above)
Comment (jcoyne) [reply app/services/cocina/mods_normalizer.rb:199]: Have you tried `Array#wrap`?

**Comment by justinlittman** [comment]
Pausing, while @arcadiafalcone considers the moving of `source` from children.

**Review by arcadiafalcone — APPROVED** [review]

**Comment by justinlittman** [comment]
Unpaused @jcoyne

**Review by jcoyne — APPROVED** [review]
