### PR TITLE
Fix Uniform title with authority test.

### LINKED ISSUE #1923: Fix "Uniform title with authority" test
In `title_info_spec.rb`.

### PR DESCRIPTION
**Pull request by justinlittman**
closes #1923

## Why was this change made?
Working tests are better than broken tests.

## How was this change tested?
Unit

## Which documentation and/or configurations were updated?
NA

### CODE REVIEW

File: spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb [hunk 1]
```diff
@@ -257,72 +257,71 @@
...
+    it_behaves_like 'MODS cocina mapping' do
+      let(:mods) do
+        <<~XML
+          <titleInfo usage="primary">
+            <title>Hamlet</title>
+          </titleInfo>
+          <titleInfo type="uniform" authority="naf" authorityURI="http://id.loc.gov/authorities/names/" valueURI="http://id.loc.gov/authorities/names/n80008522" nameTitleGroup="1">
+            <title>Hamlet</title>
+          </titleInfo>
+          <name usage="primary" type="personal" authority="naf" authorityURI="http://id.loc.gov/authorities/names/" valueURI="http://id.loc.gov/authorities/names/n78095332" nameTitleGroup="1">
```
Comment (ndushay) [inline spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb:269]: for future reference:  I've been breaking up these long lines for a single xml element - you can put a newline between attributes and even before `>`

**Review by ndushay — APPROVED** [review]
I presume you got this new mapping spec from Arcadia?  Approving on that assumption.

**Review by mjgiarlo — APPROVED** [review]
