### PR TITLE
Fix typo in relatedResource types

### LINKED ISSUE #1158: Cocina mapping error: key not found: "preceding"
```
druid:hj613mz3048 error. key not found: "preceding"
Did you mean?  "preceeding"
```

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?

Fixes #1158

### CODE REVIEW

File: app/services/cocina/to_fedora/descriptive/related_resource.rb [hunk 1]
```diff
@@ -8,7 +8,7 @@ class RelatedResource
         # see https://docs.google.com/spreadsheets/d/1d5PokzgXqNykvQeckG2ND43B6i9_CsjfIVwS_IsphS8/edit#gid=0
         TYPES = {
           'in series' => 'series',
-          'preceeded by' => 'preceeding',
+          'preceded by' => 'preceding',
           'suceeded by' => 'succeeding',
```
Comment (mjgiarlo) [inline app/services/cocina/to_fedora/descriptive/related_resource.rb:12]: Should `suceeded by` be `succeeded by`?

**Review by mjgiarlo — COMMENTED** [review]
Question about another possible typo

File: app/services/cocina/to_fedora/descriptive/related_resource.rb (hunk 1 above)
Comment (jcoyne) [reply app/services/cocina/to_fedora/descriptive/related_resource.rb:12]: Yes, thanks!

**Review by mjgiarlo — APPROVED** [review]
